### ISSUE TITLE
Missing json dependency in testrunner.py

### ISSUE THREAD

**Issue by tosyu** [rtakacs/remote-testrunner#15]
```bash
Traceback (most recent call last):
  File "driver.py", line 96, in <module>
    main()
  File "driver.py", line 93, in main
    testrunner.run(options.public)
  File "/home/tosyu/Projects/remote-testrunner/API/testrunner/testrunner.py", line 165, in run
    self.__save(is_publish)
  File "/home/tosyu/Projects/remote-testrunner/API/testrunner/testrunner.py", line 102, in __save
    data = json.load(result_file)
```

**Comment by robertsipka** [comment]
@tosyu : The project was moved to the https://github.com/Samsung/js-remote-test site.
This issue is already fixed there. 
@rtakacs : Please close this project here.

**Comment by tosyu** [comment]
@robertsipka leave it as it is, I changed my upstream remote to the new one, sorry for the confusion
